<a href="https://colab.research.google.com/github/Elango-Kannan-00/GenAI-Apex/blob/main/Tranfromers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from transformers import pipeline

In [20]:
import pandas as pd

In [21]:
data=pd.read_excel("/content/Employee Sample Data.xlsx",header=0)

In [37]:
data=data.dropna()

In [38]:
data

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59.0,1997-11-29,99975.0,0.0,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50.0,2006-10-26,163099.0,0.2,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26.0,2019-09-27,84913.0,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55.0,1995-11-20,95409.0,0.0,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,nan,nan,nan,nan,nan,nan,nan,nan,NaT,nan,nan,nan,nan,NaT
993,nan,nan,nan,nan,nan,nan,nan,nan,NaT,nan,nan,nan,nan,NaT
994,nan,nan,nan,nan,nan,nan,nan,nan,NaT,nan,nan,nan,nan,NaT
995,nan,nan,nan,nan,nan,nan,nan,nan,NaT,nan,nan,nan,nan,NaT
996,nan,nan,nan,nan,nan,nan,nan,nan,NaT,nan,nan,nan,nan,2018-01-08

In [24]:
from transformers import AutoTokenizer, AutoModelForTableQuestionAnswering

In [25]:
model='google/tapas-large-finetuned-wtq'

In [26]:
tokenizer=AutoTokenizer.from_pretrained(model)

In [27]:
tokenizer

TapasTokenizer(name_or_path='google/tapas-large-finetuned-wtq', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]', 'additional_special_tokens': ['[EMPTY]']}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[EMPTY]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [28]:
model=AutoModelForTableQuestionAnswering.from_pretrained(model)

In [29]:
tqapipe=pipeline(task="table-question-answering",model=model,tokenizer=tokenizer)

Device set to use cpu

In [41]:
tqapipe(table=data,query="tell me the name of E00549")

{'answer': 'Isabella Xi',
 'coordinates': [(15, 1)],
 'cells': ['Isabella Xi'],
 'aggregator': 'NONE'}